news/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$',Index.as_view(), name='index'),
    url(r'^changePlatformGame/(?P<query>.+)/$',ChangePlatformGame.as_view(),name='changePlatformGame'),
    url(r'^faq/$',Faq.as_view(),name='faq'),
    url(r'^changelog/$',Changelog.as_view(),name='changelog'),
    url(r'^preview/(\d+)/$',PreviewNews.as_view(),name='preview'),
    url(r'^showone/(\d+)/$',WatchOneNews.as_view(),name='showOne'),
    url(r'^searchnews/$',SearchNews.as_view(),name='searchNews'),
    url(r'^loadImages/(\d+)/$',LoadImages.as_view(),name='loadImages')
]

shortgamenews/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^patata/', admin.site.urls),
    url(r'^',include('news.urls',namespace='news'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
import os
from datetime import datetime
from django.core.exceptions import *
from sorl.thumbnail import ImageField
from sgnModules.SgnImages import changeImagePath

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name + '(Instance)'

class Platform(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Game(models.Model):
    name = models.CharField(max_length = 255,unique=True)
    web = models.URLField(blank=True)
    platform = models.ManyToManyField(Platform,blank=True)

    def __str__(self):
        return self.name

def changePath(instance,filename):
    if(instance.game):
        if(instance.platform):
            return "photo/{0}/{1}/{2}/{3}".format(
                instance.game.name.replace(' ','_').lower(),
                instance.platform.name.replace(' ','_').lower(),
                datetime.now().strftime("%d-%m-%Y"),
                filename)
        else:
            return "photo/{0}/{1}/{2}".format(
                instance.game.name.replace(' ','_').lower(),
                datetime.now().strftime("%d-%m-%Y"),
                filename)


    if(instance.platform):
        return "photo/{0}/{1}/{2}".format(
            instance.platform.name.replace(' ','_').lower(),
            datetime.now().strftime("%d-%m-%Y"),
            filename)

    return "photo/{0}/{1}/{2}".format(
        'noPlatform',
        datetime.now().strftime("%d-%m-%Y"),
        filename)

class Picture(models.Model):
    name = models.CharField(max_length=255)
    image = ImageField(upload_to=changeImagePath)
    game = models.ForeignKey(Game,blank=True,null=True)
    platform = models.ForeignKey(Platform,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)


    def save(self, *args, **kwargs):
        if self.id:
            kwargs['update_fields'] = None

        super(Picture, self).save(*args, **kwargs) # Call the "real" save() method.


    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length = 255)
    text = models.TextField()
    nameSource = models.CharField(max_length = 255,blank=True)
    source = models.URLField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)
    category = models.ForeignKey(Category,blank=True,null=True)
    games = models.ManyToManyField(Game,blank=True)
    platforms = models.ManyToManyField(Platform,blank=True)
    images = models.ManyToManyField(Picture,blank=True)

    class Meta:
        ordering = ['-date']
        permissions = (("can_preview", "Can preview a news"),)

    def __str__(self):
        return self.title

news/forms.py
from django import forms

class SearchNewsForms(forms.Form):
    #title = forms.CharField(label='Title news', max_length=255)
    games = forms.CharField(label='Game', max_length=255, required=False)
    platforms = forms.CharField(label='Platform', max_length=255, required=False)
    category = forms.CharField(label='Category', max_length=255, required=False)
    order = forms.ChoiceField(label='Order by date',choices=[['','older'],['-','newer']],required=False)

news/views.py
from django.shortcuts import render
from django.views import View
from .models import News, Picture, Game, Platform, Category
from django.utils.html import escape, strip_tags, mark_safe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import markdown
from sorl.thumbnail import get_thumbnail
from django.http import JsonResponse
from django.core import serializers
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import SearchNewsForms
from sgnModules.SgnJson import autocomplete, querySetToJson
#from django.db.models import Q
#from django.db.models.query import QuerySet

class Index(View):
    templateName = 'news/show.html'
    def get(self,request,*args,**kwargs):
        news = News.objects.filter(published=True)[:30]
        paginator = Paginator(news,10)
        page = request.GET.get('page')
        try:
            news = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            news = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            news = paginator.page(paginator.num_pages)

        #for n in news:
        #    n.text = markdown.markdown(strip_tags(n.text))
        return render(request,self.templateName,{'news': news,'path': request.get_full_path()})

class ChangePlatformGame(View):
    def get(self,request,*args,**kwargs):
        test = serializers.deserialize('json',kwargs['query'])
        return JsonResponse({'da': test[0]})

    def post(self,request,*args,**kwargs):
        return JsonResponse({'da': 'weeee'})

class LoadImages(View):
    def get(self,request,*args,**kwargs):
        pictures = News.objects.get(pk=args[0]).images.all()
        finalPictures = []
        for pict in pictures:
            finalPictures.append({
                'small': get_thumbnail(pict.image, '640x480', quality=60).url,
                'large': pict.image.url,
                'name': pict.name,
                'id': pict.id
            })
        return JsonResponse({'pictures': finalPictures})

class Faq(View):
    templateName = 'news/faq.html'
    def get(self,request,*args,**kwargs):
        return render(request,self.templateName)

class Changelog(View):
    templateName = 'news/changelog.html'
    def get(self,request,*args,**kwargs):
        return render(request,self.templateName)

class PreviewNews(PermissionRequiredMixin, View):
    templateName = 'news/show.html'
    permission_required = 'news.can_preview'
    raise_exception = True
    def get(self,request,*args,**kwargs):
        preview = News.objects.filter(pk=args[0])
        #for n in preview:
        #    n.text = markdown.markdown(strip_tags(n.text))
        return render(request,self.templateName,{'news': preview})

class WatchOneNews(View):
    templateName = 'news/show.html'
    def get(self,request,*args,**kwargs):
        news = News.objects.filter(pk=args[0],published=True)
        #for n in news:
        #    n.text = markdown.markdown(strip_tags(n.text))
        return render(request,self.templateName,{'news': news})

class SearchNews(View):
    templateName = 'news/searchNews.html'
    def get(self,request,*args,**kwargs):
        #titleNews = News.objects.values('title')
        form = SearchNewsForms()
        dataJson = {
            'games': autocomplete('name',Game.objects.values('name')),
            'platforms': autocomplete('name',Platform.objects.values('name')),
            'category': autocomplete('name',Category.objects.values('name'))
        }
        return render(
            request,
            self.templateName,
            {
                'form': form,
                'dataJson': dataJson
            }
        )
    def post(self,request,*args,**kwargs):
        news = News.objects.filter(published = True)
        if request.POST['games']:
            news = news.filter(games__name = request.POST['games'])

        if request.POST['platforms']:
            news = news.filter(platforms__name = request.POST['platforms'])

        if request.POST['category']:
            news = news.filter(category__name = request.POST['category'])

        news = news.order_by(request.POST['order']+'date')

        # queryset to json
        news = querySetToJson(news)

        #markdown to html
        for value in news:
            value['text'] = markdown.markdown(strip_tags(value['text']))

        return JsonResponse({'status': news})

def learnMore():
    picture = Picture.objects.get(pk=20)
    #im = get_thumbnail(picture.image, '100x100', crop='center', quality=99)
    #return get_thumbnail(picture.image, '1280x720', quality=99)
    #return picture.image

news/templates/news/changelog.html
{% extends "news/index.html" %}
{% block main %}
<h1>Changelog</h1>

<dl class='uk-margin-bottom'>
  <dt>31-03-2017</dt>
  <dd>- Form to search news</dd>
  <dd>- Pagination in one unique news is not shown</dd>
</dl>

{% endblock %}

news/templates/news/faq.html
{% extends "news/index.html" %}
{% block main %}

<div class='uk-margin-bottom sgn-container-color sgn-padding'>
  <h1>What is shortgamenews</h1>

  <p>Here you will find short news about videogames.</p>
  <p>Many times, when you read a news, there are information that you don't need,
  and the only one thing you want to is know the important part.</p>
  <p>So that is, just the news, not more useless text.</p>
  <p>Then, you can read more news in less time.</p>

  <h1>Why do i need to load the images</h1>

  <p>I am attempting to make the <strong>front page</strong> fast and use less data on mobile.</p>
  <p>so for now, the images are not needed unless you want to watch them.</p>

  <h1>The web page is ugly</h1>

  <p>What I have been looking for is a web with colors that are easy to read and
    don't get hurt with a intense white</p>
  <p>Also, I am not good designing the interface</p>
  <p>Anyway, I will try to improve it</p>

  <h1>I have an idea to improve the web</h1>

  <p>For now, you can tell me it on <a href="#">twitter</a></p>
  <p>Later I will add a form to send me the ideas you got</p>

  <h1>Changelog</h1>

  <p>Here, I will be writing the changes I have made on shortgamenews.</p>
</div>

{% endblock %}

news/templates/news/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static "news/css/shortGameNews.css" %}" />
    <script src="{% static "news/js/jquery.min.js" %}"></script>
    {% comment %}
    <script src="{% static "news/js/uikit.min.js" %}"></script>
    <script src="{% static "news/js/components/notify.min.js" %}"></script>
    <script src="{% static "news/js/components/accordion.min.js" %}"></script>
    <script src="{% static "news/js/components/lightbox.min.js" %}"></script>
    <script src="{% static "news/js/components/sticky.min.js"%}"></script>
    {% endcomment %}
    <script src="{% static "news/js/uikitSgn.js" %}"></script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    <title>Short Game News</title>
    <link rel="icon" href="{% static "news/icon.png" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    {% block nav %}
    <nav class="uk-navbar" data-uk-sticky>
      <div class='uk-container uk-container-center'>
        <a href="{% url 'news:index' %}" class="uk-navbar-brand uk-padding-remove">
          <img class="uk-responsive-height" src="{% static "news/icon.png" %}" alt='shortgamenews'></img>
        </a>
        <ul class="uk-navbar-nav">
            <li class=""><a href="{% url 'news:searchNews' %}">Search News</a></li>
            <!--<li class=""><a href="">Changelog</a></li>-->
        </ul>
        <div class="uk-navbar-flip">
          <ul class="uk-navbar-nav">
              <li class=""><a href="{% url 'news:faq' %}">About</a></li>
              <!--<li class=""><a href="">Changelog</a></li>-->
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}
    <div class='uk-container uk-container-center'>
      <div class='uk-grid sgn-padding-top uk-margin-bottom'>
        <div class='uk-width-medium-8-10 uk-width-small-1-1'>
          {% block main %}{% endblock %}
        </div>
        <div class='uk-width-medium-2-10 uk-width-small-1-1'>
          <!--<div class="sgn-panel">
            <h2 class="sgn-panel-title">Follow me</h2>
            <div>
              <ul>
                <li><a href='https://twitter.com/shortgamenews'>Twitter</a></li>
                <li><a href='https://www.youtube.com/user/shortgamenews'>Youtube</a></li>
              </ul>
            </div>
          </div>-->
        </div>
      </div>
    </div>
    <div class="uk-block uk-block-secondary uk-contrast">
      <div class='uk-container uk-container-center'>
        <ul class='uk-subnav uk-subnav-line uk-align-left'>
          <li><a href="{% url 'news:changelog' %}">Changelog</a></li>
        </ul>
        <ul class='uk-subnav uk-subnav-line uk-align-right'>
          <li><a href="https://twitter.com/shortgamenews" target="_blank" class="uk-icon-hover uk-icon-medium uk-icon-twitter"></a></li>
          <li><a href="https://www.youtube.com/channel/UCeU9BN6qS7X1rWMkppFfZgQ" target="_blank" class="uk-icon-hover uk-icon-medium uk-icon-youtube"></a></li>
        </ul>
      </div>
    </div>
    <script src="{% static "news/js/bundle.min.js" %}"></script>
    <!-- css for cookies consent -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <!-- cookies consent-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#000"
        },
        "button": {
          "background": "#f1d600"
        }
      }
    })});
    </script>
    <!-- Google analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-65610703-3', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

news/templates/news/searchNews.html
{% extends "news/index.html" %}

{% block main %}
<div class='sgn-container-color sgn-padding uk-margin-bottom'>
  <form action="{% url 'news:searchNews' %}" method="post" class='uk-form sgn-form-searchNews'>
      {% csrf_token %}
      <fieldset>
        <div class="uk-autocomplete" data-uk-autocomplete="{source: {{ dataJson.games }} }">
        <label for="{{ form.games.id_for_label }}">{{ form.games.label }}</label>
          {{ form.games }}
        </div>

        <div class="uk-autocomplete" data-uk-autocomplete="{source: {{ dataJson.platforms }} }">
        <label for="{{ form.platforms.id_for_label }}">{{ form.platforms.label }}</label>
          {{ form.platforms }}
        </div>

        <div class="uk-autocomplete" data-uk-autocomplete="{source: {{ dataJson.category }} }">
        <label for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
          {{ form.category }}
        </div>

        <div class='uk-autocomplete'>
        <label for="{{ form.subject.id_for_label }}">{{ form.order.label }}</label>
          {{ form.order }}
        </div>
        <input type="submit" value="Submit" class='uk-button uk-button-primary'/>
      </fieldset>
  </form>
</div>
<div id='sgn-newsSearch-articles'>
</div>
{% endblock %}

news/templates/news/show.html
{% extends "news/index.html" %}
{% load static %}
{% load news_filters %}
{% block main %}

{% for n in news %}
{# Variables #}
{% url 'news:showOne' n.pk as socialUrl %}

{# Plantilla #}
<article class="uk-article">
  <h1 class="uk-article-title">{{ n.title }}</h1>
  <div class='sgn-article-padding'>
    <div class='sgn-article-meta'>
      {% if n.category %}
        <span class="uk-badge">{{ n.category.name }}</span>
      {% endif %}
      {% if n.platforms.exists %}
        {% for p in n.platforms.all %}
          <span class="uk-badge uk-badge-success">{{ p.name }}</span>
        {% endfor %}
      {% endif %}
      <p class="uk-article-meta">
        Date: {{ n.date }}
        {# Updated: {{ n.updated }} #}
      </p>
    </div>
    <hr class="uk-article-divider">
    <div class='sgn-article-text'>
      <div class='uk-grid'>
        <div class='uk-width-medium-7-10'>
            {{ n.text|mk }}
          {% if n.images.exists %}
            <div class='gallery-{{ n.id }}'>
              <button id="{{ n.id }}" class='uk-button uk-button-primary' data-sgn-images>Load images</button>
            </div>
          {% endif %}
        </div>
        <div class='uk-width-medium-3-10'>
          {% if n.games.exists %}
          <ul class="uk-nav uk-nav-side">
            <li class='uk-nav-header'>More about</li>
            {% for g in n.games.all %}
              <li><a href="{{ g.web }}" rel="nofollow" target="_blank">{{g.name}}</a></li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class='uk-width-1-1 sgn-source uk-margin-top'>
          {% if n.source %}
            <span class='uk-text-bold'>Source: <a href="{{ n.source }}" target="_blank">{{ n.nameSource }}</a></span>
          {% endif %}
        </div>
        <div class='uk-width-1-1 uk-margin-small-top'>
          {% url 'news:showOne' n.pk as socialUrl %}
          <ul class='uk-subnav uk-subnav-line'>
            {% socialButtons name='shortgamenews' url=socialUrl path=path text=n.title size='small' %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>
{% endfor %}

{% if news.paginator %}

<div class='uk-margin-top'>
  {% if news.has_previous %}
      <a class='uk-button uk-button-primary' href="?page={{ news.previous_page_number }}">previous</a>
  {% endif %}

  <span class="current">
      Page {{ news.number }} of {{ news.paginator.num_pages }}.
  </span>

  {% if news.has_next %}
      <a class='uk-button uk-button-primary' href="?page={{ news.next_page_number }}">next</a>
  {% endif %}
</div>

{% endif %}

<div id='test'>
</div>
{% endblock %}